/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_holamundondk_HolaMundoNDK */

#ifndef _Included_com_holamundondk_HolaMundoNDK
#define _Included_com_holamundondk_HolaMundoNDK
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_holamundondk_HolaMundoNDK
 * Method:    dameDatos
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_holamundondk_HolaMundoNDK_dameDatos
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
